/**
 * Supabase database types.
 *
 * ⚠️  ملف مُولّد آليًا — لا تُعدّله يدويًا.
 *     التوليد: pnpm db:types:generate   (يشتقّ الأنواع من supabase/migrations)
 *
 * عدد الجداول: 42
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      appointment_statuses: {
        Row: {
          id: string;
          organization_id: string;
          key: string;
          name_ar: string;
          category: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          key: string;
          name_ar: string;
          category?: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          key?: string;
          name_ar?: string;
          category?: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      appointments: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          reference_no: string | null;
          customer_id: string;
          service_id: string | null;
          provider_id: string | null;
          status_id: string;
          scheduled_at: string;
          duration_minutes: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          reference_no?: string | null;
          customer_id: string;
          service_id?: string | null;
          provider_id?: string | null;
          status_id: string;
          scheduled_at: string;
          duration_minutes?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          reference_no?: string | null;
          customer_id?: string;
          service_id?: string | null;
          provider_id?: string | null;
          status_id?: string;
          scheduled_at?: string;
          duration_minutes?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      approvals: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          entity_type: string;
          entity_id: string;
          step_no: number;
          approver_id: string | null;
          status: string;
          decided_at: string | null;
          note: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          entity_type: string;
          entity_id: string;
          step_no?: number;
          approver_id?: string | null;
          status?: string;
          decided_at?: string | null;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          entity_type?: string;
          entity_id?: string;
          step_no?: number;
          approver_id?: string | null;
          status?: string;
          decided_at?: string | null;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: number;
          organization_id: string;
          branch_id: string | null;
          user_id: string | null;
          action: string;
          module: string;
          entity_type: string;
          entity_id: string | null;
          old_values: Json | null;
          new_values: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          organization_id: string;
          branch_id?: string | null;
          user_id?: string | null;
          action: string;
          module: string;
          entity_type: string;
          entity_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          organization_id?: string;
          branch_id?: string | null;
          user_id?: string | null;
          action?: string;
          module?: string;
          entity_type?: string;
          entity_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      branch_services: {
        Row: {
          branch_id: string;
          service_id: string;
          is_available: boolean;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          branch_id: string;
          service_id: string;
          is_available?: boolean;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          branch_id?: string;
          service_id?: string;
          is_available?: boolean;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      branches: {
        Row: {
          id: string;
          organization_id: string;
          code: string;
          name_ar: string;
          name_en: string | null;
          phone: string | null;
          address: string | null;
          city: string | null;
          timezone: string;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          code: string;
          name_ar: string;
          name_en?: string | null;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          timezone?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          code?: string;
          name_ar?: string;
          name_en?: string | null;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          timezone?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      custody_handovers: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          shift_id: string | null;
          treasury_id: string | null;
          from_user_id: string | null;
          to_user_id: string | null;
          amount: number;
          currency: string;
          handed_at: string;
          status: string;
          note: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          shift_id?: string | null;
          treasury_id?: string | null;
          from_user_id?: string | null;
          to_user_id?: string | null;
          amount: number;
          currency?: string;
          handed_at?: string;
          status?: string;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          shift_id?: string | null;
          treasury_id?: string | null;
          from_user_id?: string | null;
          to_user_id?: string | null;
          amount?: number;
          currency?: string;
          handed_at?: string;
          status?: string;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      customers: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          code: string | null;
          full_name_ar: string;
          full_name_en: string | null;
          phone: string;
          email: string | null;
          gender: string | null;
          birth_date: string | null;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          code?: string | null;
          full_name_ar: string;
          full_name_en?: string | null;
          phone: string;
          email?: string | null;
          gender?: string | null;
          birth_date?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          code?: string | null;
          full_name_ar?: string;
          full_name_en?: string | null;
          phone?: string;
          email?: string | null;
          gender?: string | null;
          birth_date?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      departments: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          parent_id: string | null;
          code: string;
          name_ar: string;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          parent_id?: string | null;
          code: string;
          name_ar: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          parent_id?: string | null;
          code?: string;
          name_ar?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      expense_categories: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          code: string;
          name_ar: string;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          code: string;
          name_ar: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          code?: string;
          name_ar?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      expenses: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          category_id: string | null;
          transaction_id: string | null;
          treasury_id: string | null;
          reference_no: string | null;
          amount: number;
          currency: string;
          occurred_at: string;
          description: string | null;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          category_id?: string | null;
          transaction_id?: string | null;
          treasury_id?: string | null;
          reference_no?: string | null;
          amount: number;
          currency?: string;
          occurred_at?: string;
          description?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          category_id?: string | null;
          transaction_id?: string | null;
          treasury_id?: string | null;
          reference_no?: string | null;
          amount?: number;
          currency?: string;
          occurred_at?: string;
          description?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      files: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          bucket: string;
          storage_path: string;
          file_name: string;
          mime_type: string | null;
          size_bytes: number | null;
          checksum: string | null;
          entity_type: string | null;
          entity_id: string | null;
          required_permission: string | null;
          is_public: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          bucket?: string;
          storage_path: string;
          file_name: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          checksum?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          required_permission?: string | null;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          bucket?: string;
          storage_path?: string;
          file_name?: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          checksum?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          required_permission?: string | null;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      financial_entries: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          transaction_id: string;
          direction: string;
          account_ref: string | null;
          amount: number;
          currency: string;
          description: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          transaction_id: string;
          direction: string;
          account_ref?: string | null;
          amount: number;
          currency?: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          transaction_id?: string;
          direction?: string;
          account_ref?: string | null;
          amount?: number;
          currency?: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      financial_transactions: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          reference_no: string | null;
          transaction_type: string;
          amount: number;
          currency: string;
          occurred_at: string;
          status: string;
          source_module: string | null;
          source_record_id: string | null;
          idempotency_key: string | null;
          description: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          reference_no?: string | null;
          transaction_type: string;
          amount: number;
          currency?: string;
          occurred_at?: string;
          status?: string;
          source_module?: string | null;
          source_record_id?: string | null;
          idempotency_key?: string | null;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          reference_no?: string | null;
          transaction_type?: string;
          amount?: number;
          currency?: string;
          occurred_at?: string;
          status?: string;
          source_module?: string | null;
          source_record_id?: string | null;
          idempotency_key?: string | null;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      goods_receipt_items: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          goods_receipt_id: string;
          purchase_order_item_id: string | null;
          item_id: string | null;
          quantity: number;
          unit_id: string | null;
          unit_cost: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          goods_receipt_id: string;
          purchase_order_item_id?: string | null;
          item_id?: string | null;
          quantity: number;
          unit_id?: string | null;
          unit_cost?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          goods_receipt_id?: string;
          purchase_order_item_id?: string | null;
          item_id?: string | null;
          quantity?: number;
          unit_id?: string | null;
          unit_cost?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      goods_receipts: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          reference_no: string | null;
          purchase_order_id: string | null;
          supplier_id: string | null;
          warehouse_id: string;
          received_at: string;
          received_by: string | null;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          reference_no?: string | null;
          purchase_order_id?: string | null;
          supplier_id?: string | null;
          warehouse_id: string;
          received_at?: string;
          received_by?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          reference_no?: string | null;
          purchase_order_id?: string | null;
          supplier_id?: string | null;
          warehouse_id?: string;
          received_at?: string;
          received_by?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      item_categories: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          parent_id: string | null;
          code: string;
          name_ar: string;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          parent_id?: string | null;
          code: string;
          name_ar: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          parent_id?: string | null;
          code?: string;
          name_ar?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      items: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          category_id: string | null;
          base_unit_id: string | null;
          code: string;
          name_ar: string;
          name_en: string | null;
          description: string | null;
          tracking: string;
          reorder_level: number | null;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          category_id?: string | null;
          base_unit_id?: string | null;
          code: string;
          name_ar: string;
          name_en?: string | null;
          description?: string | null;
          tracking?: string;
          reorder_level?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          category_id?: string | null;
          base_unit_id?: string | null;
          code?: string;
          name_ar?: string;
          name_en?: string | null;
          description?: string | null;
          tracking?: string;
          reorder_level?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      notification_logs: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          notification_id: string;
          attempt_no: number;
          provider: string | null;
          status: string;
          response_code: string | null;
          response_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          notification_id: string;
          attempt_no: number;
          provider?: string | null;
          status: string;
          response_code?: string | null;
          response_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          notification_id?: string;
          attempt_no?: number;
          provider?: string | null;
          status?: string;
          response_code?: string | null;
          response_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      notification_templates: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          key: string;
          channel: string;
          locale: string;
          subject: string | null;
          body: string;
          variables: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          key: string;
          channel: string;
          locale?: string;
          subject?: string | null;
          body: string;
          variables?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          key?: string;
          channel?: string;
          locale?: string;
          subject?: string | null;
          body?: string;
          variables?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          channel: string;
          template_key: string | null;
          recipient: string | null;
          recipient_user_id: string | null;
          recipient_customer_id: string | null;
          subject: string | null;
          body: string | null;
          payload: Json;
          status: string;
          attempts: number;
          max_attempts: number;
          last_error: string | null;
          provider: string | null;
          provider_message_id: string | null;
          scheduled_at: string | null;
          sent_at: string | null;
          read_at: string | null;
          source_module: string | null;
          source_record_id: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          channel: string;
          template_key?: string | null;
          recipient?: string | null;
          recipient_user_id?: string | null;
          recipient_customer_id?: string | null;
          subject?: string | null;
          body?: string | null;
          payload?: Json;
          status?: string;
          attempts?: number;
          max_attempts?: number;
          last_error?: string | null;
          provider?: string | null;
          provider_message_id?: string | null;
          scheduled_at?: string | null;
          sent_at?: string | null;
          read_at?: string | null;
          source_module?: string | null;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          channel?: string;
          template_key?: string | null;
          recipient?: string | null;
          recipient_user_id?: string | null;
          recipient_customer_id?: string | null;
          subject?: string | null;
          body?: string | null;
          payload?: Json;
          status?: string;
          attempts?: number;
          max_attempts?: number;
          last_error?: string | null;
          provider?: string | null;
          provider_message_id?: string | null;
          scheduled_at?: string | null;
          sent_at?: string | null;
          read_at?: string | null;
          source_module?: string | null;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          id: string;
          code: string;
          name_ar: string;
          name_en: string | null;
          status: string;
          settings: Json;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          code: string;
          name_ar: string;
          name_en?: string | null;
          status?: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          code?: string;
          name_ar?: string;
          name_en?: string | null;
          status?: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      permissions: {
        Row: {
          id: string;
          key: string;
          module: string;
          action: string;
          name_ar: string;
          is_sensitive: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          module: string;
          action: string;
          name_ar: string;
          is_sensitive?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          module?: string;
          action?: string;
          name_ar?: string;
          is_sensitive?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          organization_id: string;
          full_name_ar: string;
          full_name_en: string | null;
          employee_code: string | null;
          phone: string | null;
          job_title: string | null;
          department_id: string | null;
          default_branch_id: string | null;
          status: string;
          is_service_provider: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          organization_id: string;
          full_name_ar: string;
          full_name_en?: string | null;
          employee_code?: string | null;
          phone?: string | null;
          job_title?: string | null;
          department_id?: string | null;
          default_branch_id?: string | null;
          status?: string;
          is_service_provider?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          full_name_ar?: string;
          full_name_en?: string | null;
          employee_code?: string | null;
          phone?: string | null;
          job_title?: string | null;
          department_id?: string | null;
          default_branch_id?: string | null;
          status?: string;
          is_service_provider?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      purchase_order_items: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          purchase_order_id: string;
          item_id: string | null;
          description: string | null;
          quantity: number;
          unit_id: string | null;
          unit_price: number;
          line_total: number | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          purchase_order_id: string;
          item_id?: string | null;
          description?: string | null;
          quantity: number;
          unit_id?: string | null;
          unit_price?: number;
          line_total?: number | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          purchase_order_id?: string;
          item_id?: string | null;
          description?: string | null;
          quantity?: number;
          unit_id?: string | null;
          unit_price?: number;
          line_total?: number | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      purchase_orders: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          reference_no: string | null;
          supplier_id: string;
          purchase_request_id: string | null;
          order_date: string;
          expected_date: string | null;
          currency: string;
          total_amount: number;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          reference_no?: string | null;
          supplier_id: string;
          purchase_request_id?: string | null;
          order_date?: string;
          expected_date?: string | null;
          currency?: string;
          total_amount?: number;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          reference_no?: string | null;
          supplier_id?: string;
          purchase_request_id?: string | null;
          order_date?: string;
          expected_date?: string | null;
          currency?: string;
          total_amount?: number;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      purchase_request_items: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          purchase_request_id: string;
          item_id: string | null;
          description: string | null;
          quantity: number;
          unit_id: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          purchase_request_id: string;
          item_id?: string | null;
          description?: string | null;
          quantity: number;
          unit_id?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          purchase_request_id?: string;
          item_id?: string | null;
          description?: string | null;
          quantity?: number;
          unit_id?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      purchase_requests: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          reference_no: string | null;
          department_id: string | null;
          requested_by: string | null;
          needed_by: string | null;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          reference_no?: string | null;
          department_id?: string | null;
          requested_by?: string | null;
          needed_by?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          reference_no?: string | null;
          department_id?: string | null;
          requested_by?: string | null;
          needed_by?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      role_permissions: {
        Row: {
          role_id: string;
          permission_id: string;
          created_at: string;
        };
        Insert: {
          role_id: string;
          permission_id: string;
          created_at?: string;
        };
        Update: {
          role_id?: string;
          permission_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      roles: {
        Row: {
          id: string;
          organization_id: string | null;
          key: string;
          name_ar: string;
          description: string | null;
          is_system: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          key: string;
          name_ar: string;
          description?: string | null;
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          key?: string;
          name_ar?: string;
          description?: string | null;
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      services: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          code: string;
          name_ar: string;
          name_en: string | null;
          description: string | null;
          default_duration_minutes: number | null;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          code: string;
          name_ar: string;
          name_en?: string | null;
          description?: string | null;
          default_duration_minutes?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          code?: string;
          name_ar?: string;
          name_en?: string | null;
          description?: string | null;
          default_duration_minutes?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      shifts: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          treasury_id: string | null;
          reference_no: string | null;
          opened_by: string | null;
          opened_at: string;
          closed_by: string | null;
          closed_at: string | null;
          opening_balance: number;
          expected_balance: number | null;
          closing_balance: number | null;
          difference: number | null;
          currency: string;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          treasury_id?: string | null;
          reference_no?: string | null;
          opened_by?: string | null;
          opened_at?: string;
          closed_by?: string | null;
          closed_at?: string | null;
          opening_balance?: number;
          expected_balance?: number | null;
          closing_balance?: number | null;
          difference?: number | null;
          currency?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          treasury_id?: string | null;
          reference_no?: string | null;
          opened_by?: string | null;
          opened_at?: string;
          closed_by?: string | null;
          closed_at?: string | null;
          opening_balance?: number;
          expected_balance?: number | null;
          closing_balance?: number | null;
          difference?: number | null;
          currency?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      stock_levels: {
        Row: {
          organization_id: string;
          branch_id: string;
          warehouse_id: string;
          item_id: string;
          quantity: number;
          updated_at: string;
        };
        Insert: {
          organization_id: string;
          branch_id: string;
          warehouse_id: string;
          item_id: string;
          quantity?: number;
          updated_at?: string;
        };
        Update: {
          organization_id?: string;
          branch_id?: string;
          warehouse_id?: string;
          item_id?: string;
          quantity?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      stock_movements: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          warehouse_id: string;
          item_id: string;
          unit_id: string | null;
          movement_type: string;
          quantity: number;
          direction: number;
          unit_cost: number | null;
          currency: string | null;
          occurred_at: string;
          source_module: string | null;
          source_record_id: string | null;
          transfer_group_id: string | null;
          reference_no: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          warehouse_id: string;
          item_id: string;
          unit_id?: string | null;
          movement_type: string;
          quantity: number;
          direction: number;
          unit_cost?: number | null;
          currency?: string | null;
          occurred_at?: string;
          source_module?: string | null;
          source_record_id?: string | null;
          transfer_group_id?: string | null;
          reference_no?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          warehouse_id?: string;
          item_id?: string;
          unit_id?: string | null;
          movement_type?: string;
          quantity?: number;
          direction?: number;
          unit_cost?: number | null;
          currency?: string | null;
          occurred_at?: string;
          source_module?: string | null;
          source_record_id?: string | null;
          transfer_group_id?: string | null;
          reference_no?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      supplier_payments: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          supplier_id: string;
          transaction_id: string | null;
          treasury_id: string | null;
          purchase_order_id: string | null;
          reference_no: string | null;
          amount: number;
          currency: string;
          paid_at: string;
          method: string;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          supplier_id: string;
          transaction_id?: string | null;
          treasury_id?: string | null;
          purchase_order_id?: string | null;
          reference_no?: string | null;
          amount: number;
          currency?: string;
          paid_at?: string;
          method?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          supplier_id?: string;
          transaction_id?: string | null;
          treasury_id?: string | null;
          purchase_order_id?: string | null;
          reference_no?: string | null;
          amount?: number;
          currency?: string;
          paid_at?: string;
          method?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      suppliers: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          code: string;
          name_ar: string;
          contact_person: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          tax_number: string | null;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          code: string;
          name_ar: string;
          contact_person?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          tax_number?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          code?: string;
          name_ar?: string;
          contact_person?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          tax_number?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      treasuries: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          code: string;
          name_ar: string;
          currency: string;
          type: string;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          code: string;
          name_ar: string;
          currency?: string;
          type?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          code?: string;
          name_ar?: string;
          currency?: string;
          type?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      treasury_movements: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          treasury_id: string;
          transaction_id: string | null;
          shift_id: string | null;
          movement_type: string;
          direction: number;
          amount: number;
          currency: string;
          occurred_at: string;
          status: string;
          source_module: string | null;
          source_record_id: string | null;
          reference_no: string | null;
          description: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          treasury_id: string;
          transaction_id?: string | null;
          shift_id?: string | null;
          movement_type: string;
          direction: number;
          amount: number;
          currency?: string;
          occurred_at?: string;
          status?: string;
          source_module?: string | null;
          source_record_id?: string | null;
          reference_no?: string | null;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          treasury_id?: string;
          transaction_id?: string | null;
          shift_id?: string | null;
          movement_type?: string;
          direction?: number;
          amount?: number;
          currency?: string;
          occurred_at?: string;
          status?: string;
          source_module?: string | null;
          source_record_id?: string | null;
          reference_no?: string | null;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      units: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          code: string;
          name_ar: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          code: string;
          name_ar: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          code?: string;
          name_ar?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      user_branches: {
        Row: {
          user_id: string;
          branch_id: string;
          is_default: boolean;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          user_id: string;
          branch_id: string;
          is_default?: boolean;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          user_id?: string;
          branch_id?: string;
          is_default?: boolean;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role_id: string;
          scope: string;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          role_id: string;
          scope?: string;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          role_id?: string;
          scope?: string;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      warehouses: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          code: string;
          name_ar: string;
          is_default: boolean;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          code: string;
          name_ar: string;
          is_default?: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          code?: string;
          name_ar?: string;
          is_default?: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
